apiVersion: v1
kind: Service
metadata:
  name: deis-database
  labels:
    name: deis-database
spec:
  ports:
    # the port that this service should serve on
  - port: 5432
    targetPort: 5432
  selector:
    name: deis-database
