apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-database
  labels:
    name: deis-database
spec:
  replicas: 1
  selector:
    name: deis-database
  template:
    metadata:
      labels:
        name: deis-database
    spec:
      containers:
      - name: db
        image: postgres:9.0.22
        ports:
        - containerPort: 5432
