apiVersion: v1
kind: Service
metadata:
  name: deis-controller
  labels:
    name: deis-controller
spec:
  ports:
    # the port that this service should serve on
  - port: 8000
    targetPort: 8000
  selector:
    name: deis-controller
